version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:80
    links:
      - "mariadb:mariadb.local"
      - "redis:redis.local"
    volumes:
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/nginx/mime.types:/etc/nginx/mime.types
      - ./conf/php-fpm/php-fpm.ini:/etc/php/8.1/fpm/conf.d/90-custom.ini
      - ./www:/var/www
      
      
      
   nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:10.10.2'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  mariadb:
    image: mariadb:10.9.3
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root

  redis:
    image: redis:7.0.5
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=127.0.0.1
      - PMA_PORT=3306
    
    depends_on:
      - mariadb
      
    links:
      - mariadb 

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:127.0.0.1:6379 
      
    ports:
      - "8081:8081"

volumes:
  mariadb-data:
  redis-data:
  nginxproxymanager-data:
