version: "3.9"
services:  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: root
    ports:
      - 8080:80
      
  #redis-commander:
  #  container_name: redis-commander
  #  hostname: redis-commander
  #  image: rediscommander/redis-commander:latest
  #  restart: always
  #  environment:
  #    - REDIS_HOSTS=local:127.0.0.1:6379  
  #  ports:
  #    - "8081:8081"
      

      
